---
name: Docker Build from development branch

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

env:
  CI_IMAGE_NAME: 'ghcr.io/cradle8810/imagemagic-image'

jobs:
  "build_for_deployment_branch":
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Kick Buildx
        uses: docker/setup-buildx-action@v1

      # https://github.com/crazy-max/ghaction-docker-meta#latest-tag
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ env.CI_IMAGE_NAME }}

      # https://github.com/marketplace/actions/docker-login#github-container-registry
      # Make your access key following this instructions, and add access key as $CR_PAT on Repository Secrets
        # https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - name: docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
